name: Automatic Release

on: 
  push: 
    tags:
      - 'v*'

jobs: 
  relesae: 
    runs-on: ubuntu-latest
    steps:
      - name: Bulid
        id: build
        uses: actions/checkout@v2
        uses: actions/setup-node@v2
        with:
          node-version: '16'
        run: npm ci
        run: npm run webchat
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }} - EDIT ME
          draft: true
          prerelease: false
      - name: Upload Release Assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/webchat.js
          asset_name: webchat.js
          asset_content_type: application/javascript
         