name: Automatic Release

on: 
  push: 
    tags:
      - 'v*'

jobs: 
  relesae: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build
        run: npm ci && npm run build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.js
          body: |
            ### Potentially breaking changes

            ### New Features

            ### Bug Fixes

            ### Improvements
            

         